### ISSUE TITLE
Support for touch icons, manifest files, favicon etc. 

### ISSUE THREAD

**Issue by MitchAnderson93** [qld-gov-au/qgds-tokens#17]
Any plans to support standardised images? e.g. stored on public CDN with references in templates

Examples:
- Manifest.json file/attributes
- Touch icons (mobile) at various sizes 
- Favicons at various sizes
- Opengraph tiles (as seen in social media shares) 
etc

**Comment by pedroportella** [comment]
QGDS-Assets will hold and distribute all iconography, imagery, footage, videos, clips and font files. 
QGDS-Tokens will only hold and distribute tokens following the single-responsibility principle.
